// initialize
export const UPDATE_WINDOW_DIMENSIONS = "UPDATE_WINDOW_DIMENSIONS";

// register
export const SAVE_REGISTER_CONSENT_ERRORS = "SAVE_REGISTER_CONSENT_ERRORS";
export const SUCCESSFULLY_REGISTERED_CONSENT =
  "SUCCESSFULLY_REGISTERED_CONSENT";
export const SAVE_CODE_ERROR = "SAVE_CODE_ERROR";
export const NEXT_STEP = "NEXT_STEP";
export const REMOVE_CODE_ERROR = "REMOVE_CODE_ERROR";

// experiment
export const COMPLETED_TRIAL = "COMPLETED_TRIAL";
