// initialize
export const UPDATE_WINDOW_DIMENSIONS = "UPDATE_WINDOW_DIMENSIONS";

// register
export const SAVE_REGISTER_ERRORS = "SAVE_REGISTER_ERRORS";

export const SAVE_CODE_ERROR = "SAVE_CODE_ERROR";
export const NEXT_STEP = "NEXT_STEP";
export const REMOVE_CODE_ERROR = "REMOVE_CODE_ERROR";
